name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: yourusername
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: yourdatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U yourusername"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx

    - name: Wait for DB
      run: |
        sudo apt-get update && sudo apt-get install -y netcat-openbsd
        until nc -z localhost 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 3
        done

    - name: Set DATABASE_URL
      env:
        POSTGRES_USER: yourusername
        POSTGRES_PASSWORD: yourpassword
        POSTGRES_DB: yourdatabase
      run: echo "DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB" >> $GITHUB_ENV

    - name: Run migrations
      run: |
        alembic upgrade head
        python migrations/init_db.py

    - name: Run tests
      run: |
        pytest